modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Tigercrl/GokiSkills/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "gokiskills"
version = "${version}"
displayName = "GokiSkills"
authors = "Tigercrl"
description = '''
Unlock and upgrade your skills by experience points!
'''
displayURL = "https://modrinth.com/mod/gokiskills"
logoFile = "icon.png"

[[dependencies.gokiskills]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gokiskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gokiskills]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"
