modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/Tigercrl/GokiSkills/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "gokiskills"
version = "${version}"
displayName = "GokiSkills"
authors = "Tigercrl"
description = '''
Unlock and upgrade your skills by experience points!
'''
displayURL = "https://modrinth.com/mod/gokiskills"
logoFile = "assets/gokiskills/icon.png"
updateJSONURL = "https://api.modrinth.com/updates/gokiskills/forge_updates.json"

[[mixins]]
config="gokiskills.mixins.json"

[[dependencies.gokiskills]]
modId = "neoforge"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gokiskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,1.20.7)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gokiskills]]
modId = "architectury"
mandatory = true
versionRange = "[12.1.4,)"
ordering = "AFTER"
side = "BOTH"
